import "./globals.css";
import { Figtree, Lexend, Plus_Jakarta_Sans } from "next/font/google";
import LayoutGoogleTranslate from "@/components/layoutGoogleTranslate";
import { ThemeProvider as NextThemesProvider } from "next-themes";

const name = process.env.NEXT_PUBLIC_NAME;
export const metadata = {
  title: name,
  // description: "Generated by create next app",
  icons: {
    icon: "/logo.png",
  },
};

const body = Lexend({
  // weight: ["300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={body.className} suppressHydrationWarning>
      <body className="2xl:mx-auto 2xl:max-w-7xl">
        <NextThemesProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <div className="fixed bottom-5 right-4 z-10 mx-auto">
            <LayoutGoogleTranslate />
          </div>
        </NextThemesProvider>
      </body>
    </html>
  );
}
